### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by ovidr**
Moved link of blog inside of sentence
Used numbering bullet points for installation steps
Switched the two environments from sentences to bullet points
Changed "-" to ":" to representing listing clearly
Changed all run-on sentences in the paragraph under "Experimentation" into complete sentences
Replaced faded check boxes to "✓" and "✗" to better represent lists

### CODE REVIEW

**Comment by ovidr** [comment]
Hello,
I have made some changes to your README file. The reason is that I am tasked by my professor to help github projects be more easy to read and understand. I have not made any changes to your code.

Thank you for your time.

**Comment by jangirrishabh** [comment]
Hello @ovidr your changes look nice, thank you for your time. I would further suggest you to please revert the check box style under "Tasks" as it suggests that the task is yet to be done and just putting a cross makes it look like the task failed, which is not the case. Let me know when you patch this so that I can merge your pull request.

**Comment by ovidr** [comment]
Done. Thank you for the feedback!

**Comment by jangirrishabh** [comment]
Done! Thank you for your contribution @ovidr

**Pull request merged**
